name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Koyeb
        uses: koyeb/koyeb-action@v1
        with:
          koyeb_organization: ${{ secrets.KOYEB_ORGANIZATION }}
          koyeb_app: ${{ secrets.KOYEB_APP }}
          koyeb_service: ${{ secrets.KOYEB_SERVICE }}
          koyeb_secret: ${{ secrets.KOYEB_API_TOKEN }}